### ISSUE TITLE
Add "page" type for stand-alone (unlisted) subpages

### ISSUE THREAD

**Issue by gammaw** [revnandi/em-cms#10]
**Issue**: post or pub types cannot be used for something like /privacy

There is one for privacy yes, but it's one + the route cannot be edited. 

**Quick fix**: make existing policy page URL editable.

**Comment by revnandi** [comment]
the ssg builds pages from page files in the repo (ie privacy-policy.astro -> /privacy-policy) or dynamically from a template based on data from a collection endpoint from strapi

to be able to add pages from the cms with custom urls I need to create a page collection, change the menu so it supports dynamic data etc

**Comment by gammaw** [comment]
@revnandi thanks! let's close it for now, cause I'm not sure if we need extra pages atm.
